apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'dev-asset-management'
spec:
  project: dev-bayen
  source:
    repoURL: >-
      https://repository_ro_key:u3E2NxbpfG8brAhvr3eb@gitlab.com/target-digital-transformation/devops-group/manifests/bayen/asset-management.git
    path: helm/0-0-dev-gke-dev/asset-management
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://35.232.144.74'
    namespace: dev-meeraspace-bayen
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true


