apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'dev-tendering-fe'
spec:
  project: dev-tendering
  source:
    repoURL: >-
      https://repository_ro_key:q6umx-nVyvW-faQNc-h6@gitlab.com/target-digital-transformation/devops-group/manifests/tendering/tendering-fe.git
    path: helm/0-0-dev-gke-dev/tendering-fe
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://35.232.144.74'
    namespace: dev-meeraspace-tendering
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true


