apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ''
spec:
  project: dev-chatbot
  source:
    repoURL: >-
      https://repository_ro_key:qVWPd3RPEgXoyjv88aX6@gitlab.com/target-digital-transformation/devops-group/manifests/chatbot/elevate-chatbot.git
    path: helm/0-0-dev-gke-dev/elevate-chatbot
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://35.232.144.74'
    namespace: dev-meeraspace-chatbot
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true


